In [1]:
import sys
import numpy as np

# Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
# easy to create one, just like a normal array inside np.array
a = np.array([1, 2, 3, 4])
b = np.array([0, .5, 1, 1.5])

In [5]:
# to access elements
a[0], a[1]

(1, 2)

In [7]:
# accessing from ranges
a[2:4]

array([3, 4])

In [10]:
# there is something different about numpy arrays called multiindexing

# you have to send a list of the indices that you want to select, and then pass that
# the result is another numpy array
b[[0, 2, -1]]

array([0. , 1. , 1.5])

Array type

In [14]:
# numpy automatically assigns a type, but you can specify at the start
a.dtype

dtype('int32')

In [15]:
b.dtype

dtype('float64')

In [16]:
np.array([1,2,3,4], dtype=np.float)

array([1., 2., 3., 4.])

In [ ]:
# you can store strings and objects, but usually numpy is used for numeric purposes