# Multidimensional Arrays

In [4]:
import numpy as np
# 2D array matrices

In [5]:
A = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

In [7]:
# we can check shape
A.shape

(2, 3)

In [9]:
# you can check number of dimensions
A.ndim

2

In [10]:
# you have to be careful, if the dimensions dont match, then it will just fall back to python objects

#### Indexing and Slicing Matrices

In [11]:
# for a square matrix, you can find the row, or specific points
A[1]

array([4, 5, 6])

In [12]:
# and a specific part
A[1][0]

4

In [14]:
# however, you can also get it like the following:
# A[d1, d2, d3, d4...]
A[1, 0]

# this syntax will also allow slicing

4

In [15]:
A[:, :2]

array([[1, 2],
       [4, 5]])

In [17]:
# you can also modify existing rows or parts of arrays
A[1] = np.array([10, 10, 10])
A

array([[ 1,  2,  3],
       [10, 10, 10]])

In [19]:
# or you can also do the following, if you want to set everything
A[0] = 0
A

array([[ 0,  0,  0],
       [10, 10, 10]])