# Broadcasting and Vectorized Operations

In [22]:
import numpy as np
a = np.array([0,1,2,3])

In [23]:
# vectorized are between arrays and arrays and scalars

In [24]:
# now, we can do operations with entire arrays
a+10


array([10, 11, 12, 13])

In [25]:
# the operations are vectorized, and everything is broadcasted across to each element in the array

In [26]:
a
# however we can see that we are creating a new array each time, and the array is not changed, unless of course we change it

array([0, 1, 2, 3])

In [27]:
a += 1
print(a)
a -= 1

[1 2 3 4]


In [28]:
# we can even loop like following
[i * 10 for i in a]

[0, 10, 20, 30]

In [33]:
a = np.arange(4)
a


array([0, 1, 2, 3])

In [35]:
b = np.arange(4) +4
b

array([4, 5, 6, 7])

In [36]:
a+b

array([ 4,  6,  8, 10])

In [37]:
# for this to work, the arrays need to be alligned and be the same shape. The operation occurs very fast