# Boolean Arrays

In [2]:
import numpy as np
a = np.arange(4)
a

array([0, 1, 2, 3])

In [6]:
# 3 ways to get multiindexes:

# way #1, traditional python way:
a[0], a[1]

(0, 1)

In [5]:
# way #2, multiindex selection
a[[0, -1]]

array([0, 3])

In [4]:
# however, you can also use logic/boolean operators to the numpy arrays

In [8]:
# way #3, with boolean to indicate which elements you are selecting:
a[[True, False, False, True]]

array([0, 3])

In [9]:
# you will not write this much for huge arrays, but you can also use the arrays that arrive by broadcasting boolean operations in order to return what you need

a>=2

array([False, False,  True,  True])

In [11]:
# aha! now we can input it and find the values, and you can combine the operations
a[a>=2]

array([2, 3])

In [12]:
# the advantage of this is that you can filter through the arrays just by using familiar syntax that is  intuitive.

# for example, we can get all the values that are greater than the mean

a[a>a.mean()]

array([2, 3])

In [13]:
# now, we can use this query method to get elements of the data that can be returned

# we can also return all the values that are not greater than the mean
a[~(a>a.mean())]

array([0, 1])

In [26]:
# now, we can construct a random array like the following
A = np.random.randint(100, size = (3,3))
A

array([[56, 64, 42],
       [84, 69, 11],
       [31, 48, 44]])

In [27]:
A[A>A.mean()]

array([56, 64, 84, 69])

In [28]:
# we can generate a matrix of boolean values for all the values that have some relationship:
A>30

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [29]:
# and now we can use it:
A[A>30]

array([56, 64, 42, 84, 69, 31, 48, 44])