# Linear Algebra

In [2]:
import numpy as np

In [7]:
A = np.random.randint(20, size = [3,3])
A

array([[12, 17, 10],
       [ 9, 10,  3],
       [19,  6, 17]])

In [8]:
B = np.random.randint(20, size = [3,3])
B

array([[16, 12,  0],
       [ 9, 18, 17],
       [14,  8, 10]])

In [9]:
# we can also do linear algebra
A.dot(B)

array([[485, 530, 389],
       [276, 312, 200],
       [596, 472, 272]])

In [10]:
A @ B

array([[485, 530, 389],
       [276, 312, 200],
       [596, 472, 272]])

In [11]:
B.T

array([[16,  9, 14],
       [12, 18,  8],
       [ 0, 17, 10]])

In [12]:
B.T @ A

array([[539, 446, 425],
       [458, 432, 310],
       [343, 230, 221]])