# Useful Numpy Functions

### random

In [1]:
import numpy as np


In [3]:
# you can create an array of size 2, 1 of random numbers from 0 to 1
np.random.random(size=2)

array([0.73139508, 0.15583029])

In [7]:
# you can also get a random value distributed based on probabilities in the normal distribution 
np.random.normal(size=2)

array([-0.39773644,  0.81595209])

In [13]:
# whereas random takes simply the size and creates it, rand is one that simply take the dimensions of the array as an input and creates an array of those dimensions
np.random.rand(2, 4, 2)

array([[[0.22152973, 0.67732355],
        [0.5663039 , 0.28327673],
        [0.88666198, 0.16112551],
        [0.50350466, 0.08043142]],

       [[0.85231097, 0.06099949],
        [0.66583353, 0.87584429],
        [0.71480343, 0.31345395],
        [0.90215943, 0.91360125]]])

### arange

In [16]:
# you can create an array of numbers from 0 to the number given
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# or from the range given
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [18]:
# or given a range and a step
np.arange(5, 10, 0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### reshape

In [28]:
# given an array, no matter the dimensions you can appropriately reshape it to what you want
a = np.arange(20)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
a = a.reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
a = a.reshape(10, 2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

### linspace

In [39]:
# linspace allows you to create an array with numbers in a range, in the format following:

# np.linspace(start, stop, lengthOfArray, boolean stopIncluded (optional))

np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [37]:
np.linspace(0, 1, 21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [40]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### zeros, ones, empty

In [41]:
# you can create a numpy array with only zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.zeros([3, 3], dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [46]:
# or with ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [47]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
# empty allows you to get an array without specifying entries
np.empty(5)

array([1., 1., 1., 1., 1.])

In [49]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [51]:
np.empty((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### identity and eye

In [53]:
# identity makes a numpy array with the diagonal across a 1
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
# k is the shift to the left or to the right
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.eye(8, 4, k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
"Hello World"[6]

'W'